name: Sync Labels

on:
  push:
    branches: [main, master]
    paths:
      - .github/labels.yml
      - .github/workflows/label-sync.yml
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
        with:
          yaml-file: .github/labels.yml
          skip-delete: false
